/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package keystroke;

import java.awt.event.KeyEvent;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 * 
 *
 * @author Walter
 */
public class View extends javax.swing.JFrame {

    /**
     * Creates new form View
     */
    public View() {
        initComponents();
        
        jLabel2.setVisible(false);
        jButton2.setVisible(false);
        jLabel3.setText("Bienvenido");
        jLabel1.setVisible(false);
        jTextField2.setVisible(false);
        jTextArea1.setVisible(false);
        
        
       // t.start();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        jLabel1.setText("Prototipo de KeyStroke");

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton1.setText("Accesar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Nuevo intento");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setText("Intentos:");

        jTextField2.setText("Datos1");

        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField3KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField3KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField3KeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextField3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 479, Short.MAX_VALUE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3)))))
                .addGap(13, 13, 13)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(jTextField1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

Metodo m= new Metodo();    
 boolean exist;
 int key,S,contador=0,bandera1=0,bandera2=0,Clave2;
 int contador1=0,contador2=0;
         
 long Total=0,pulsada,PP=0;
 long SoltarPulsar=0, SumSP=0;
 int intentos=0;
String Especial;        
 char tecla;
 long time_start, time_end;
 long ID_start,ID_end;
 long Pulso1, Pulso2;
 long finish,Permanencia,Ausencia;
 int conteoPush=0, conteoDrop=0;
 boolean normal=true;
long Reporte[]= new long[10];
long RsoltarPulsar[]= new long[10];
long ArrayPP[]= new long [10];
long ArrayTF[]= new long[10];
String cadena="",Persona="",Name="";
String Pegar[]= new String[100];
//------------------------------
//Arreglos donde estarán los valores de cada pulsación o solte
long Pulsada[]= new long[10];
long Soltada[]= new long[10];
long Resultados[]= new long[19];
long nResultados[]= new long[12];

long Pul_ID[]= new long[7];
long Sol_ID[]=new long[7];

//-------------------------------
//**********************************************************************
//VAriables que ya me van a servir
long nS1,nS2,nS3,nS4,nS5,nS6,nS7,nS8,nS9,nS10;
long nP1,nP2,nP3,nP4,nP5,nP6,nP7,nP8,nP9,nP10;

long S1,S2,S3,S4,S5,S6,S7,S8,S9,S10;
long P1,P2,P3,P4,P5,P6,P7,P8,P9,P10;


//**********************************************************************
 //--------------------------------------------
Calendar T = Calendar.getInstance();
long Inicio,Final,TotalF;
 //--------------------------------------------
  
    
    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed

conteoPush++;
key = evt.getKeyCode();
tecla= evt.getKeyChar();
S= evt.getExtendedKeyCode();


if(S==8){
dispose();
View.main(Pegar);
}

if(contador<1){
Inicio= System.currentTimeMillis();
contador=3;
}


//System.out.println("PUSH " + tecla + " inicia: "+ time_start );
if(conteoPush>1){
    //Se verifica que solo tome el primer PUSH
}else{
if(S==16){
pulsada= System.currentTimeMillis();
PP=pulsada+pulsada;
Especial="Shift";    
time_start= System.currentTimeMillis();
Pulso2= System.currentTimeMillis();
jTextArea1.append("PUSH [ " + Especial + " ] inicia: "+ time_start  + '\n');
conteoPush=0;    
normal=false;
}if(S==17){
    pulsada= System.currentTimeMillis();
    PP=pulsada+pulsada;
Especial="Control";    
time_start= System.currentTimeMillis();
Pulso2= System.currentTimeMillis();
jTextArea1.append("PUSH [ " + Especial + " ] inicia: "+ time_start  + '\n');
conteoPush=0;        
normal=false;
}if(S==20){
pulsada= System.currentTimeMillis();   
PP=pulsada+pulsada;
Especial="Bloq Mayus";    
time_start= System.currentTimeMillis();
Pulso2= System.currentTimeMillis();
jTextArea1.append("PUSH [ " + Especial + " ] inicia: "+ time_start  + '\n');
conteoPush=0; 
normal=false;
}if(S==127){
pulsada= System.currentTimeMillis();  
PP=pulsada+pulsada;
Especial="Suprimir";    
time_start= System.currentTimeMillis();
Pulso2= System.currentTimeMillis();
jTextArea1.append("PUSH [ " + Especial + " ] inicia: "+ time_start  + '\n');
conteoPush=0;    
normal=false;
}if(S==8){
pulsada= System.currentTimeMillis();  
PP=pulsada+pulsada;
Especial="Retroceso";    
time_start= System.currentTimeMillis();
Pulso2= System.currentTimeMillis();
jTextArea1.append("PUSH [ " + Especial + " ] inicia: "+ time_start  + '\n');
conteoPush=0; 
normal=false;
}if(S==36){
pulsada= System.currentTimeMillis(); 
PP=pulsada+pulsada;
Especial="Inicio";    
time_start= System.currentTimeMillis();
Pulso2= System.currentTimeMillis();
jTextArea1.append("PUSH [ " + Especial + " ] inicia: "+ time_start  + '\n');
conteoPush=0;    
normal=false;
}if(S==35){
pulsada= System.currentTimeMillis(); 
PP=pulsada+pulsada;
Especial="Fin";    
time_start= System.currentTimeMillis();
Pulso2= System.currentTimeMillis();
jTextArea1.append("PUSH [ " + Especial + " ] inicia: "+ time_start  + '\n');
conteoPush=0;    
normal=false;
}
if(normal==true){
   
pulsada= System.currentTimeMillis(); 
PP=pulsada+pulsada;
time_start= System.currentTimeMillis();
Pulso2= System.currentTimeMillis();
 jTextArea1.append("PUSH [ " + tecla + " ] inicia: "+ time_start  + '\n');

 conteoPush=0;    
 Pulsada[bandera1]=time_start;
 bandera1++; 
}
    
    
normal=true;    
    
SumSP= Pulso1-Pulso2; 
SoltarPulsar= SumSP+SumSP;

}

    }//GEN-LAST:event_jTextField1KeyPressed

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        // TODO add your handling code here:
        conteoDrop++;
        
        time_end= System.currentTimeMillis();
        
        finish= time_end-time_start;
        
        Permanencia= time_end-time_start;
        Ausencia= time_start - time_end;
        //System.out.println("DROP "+tecla+" termina: "+time_end);
        if(conteoDrop>1){
            
        }else{
            
if(S==16){
Especial="Shift";    
Pulso1= System.currentTimeMillis();
time_start= System.currentTimeMillis();
jTextArea1.append("DROP [ " + Especial + " ] termina: "+ time_end  + '\n');
conteoDrop=0;    
normal=false;
}if(S==17){
Especial="Control";    
Pulso1= System.currentTimeMillis();
time_start= System.currentTimeMillis();
jTextArea1.append("DROP [ " + Especial + " ] termina: "+ time_end  + '\n');
conteoDrop=0;        
normal=false;
}if(S==20){
Especial="Bloq Mayus";    
Pulso1= System.currentTimeMillis();
time_start= System.currentTimeMillis();
jTextArea1.append("DROP [ " + Especial + " ] termina: "+ time_end  + '\n');
conteoDrop=0; 
normal=false;
}if(S==127){
Especial="Suprimir";    
Pulso1= System.currentTimeMillis();
time_start= System.currentTimeMillis();
jTextArea1.append("DROP [ " + Especial + " ] termina: "+ time_end  + '\n');
conteoDrop=0;    
normal=false;
}if(S==8){
Especial="Retroceso";    
Pulso1= System.currentTimeMillis();
time_start= System.currentTimeMillis();
jTextArea1.append("DROP [ " + Especial + " ] termina: "+ time_end  + '\n');
conteoDrop=0; 
normal=false;
}if(S==36){
Especial="Inicio";    
Pulso1= System.currentTimeMillis();
time_start= System.currentTimeMillis();
jTextArea1.append("DROP [ " + Especial + " ] termina: "+ time_end  + '\n');
conteoDrop=0;    
normal=false;
}if(S==35){
Especial="Fin";    
Pulso1= System.currentTimeMillis();
time_start= System.currentTimeMillis();
jTextArea1.append("DROP [ " + Especial + " ] termina: "+ time_end  + '\n');
conteoDrop=0;    
normal=false;
}
if(normal==true){
        jTextArea1.append("DROP [ " + tecla + " ] termina: "+ time_end  + '\n');
        //System.out.println("Terminó en: "+finish );
        jTextArea1.append("Terminó en: " + finish + '\n');
        jTextArea1.append("________________________________"  + '\n');    
        conteoDrop=0;
        Total=Total+finish;
 Soltada[bandera2]=time_end;
 bandera2++;
}
    
    
normal=true;               
            
            
        
        }
        
        
    }//GEN-LAST:event_jTextField1KeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
Acceso ac= new Acceso();

String pass= jTextField1.getText();
String us=jTextField3.getText();

ac.VerificaUser(us, pass);



if(jTextField2.getText().equals("")){
    
JOptionPane.showMessageDialog(this, "Tiene que poner su nombre");
    
}else{

    if(ac.existe){
if(ac.tipo=="nuevo"){
NewPass n=new NewPass();
n.show();
dispose();
}else{        
exist=true;    
System.out.println("Tipo: "+ac.tipo);
System.out.println("id: "+ac.getUser());
System.out.println("todo bien todo bien");





   try {
        nombre();    
    } catch (IOException ex) {
        Logger.getLogger(View.class.getName()).log(Level.SEVERE, null, ex);
    }
   
}
    
    
/*Final= System.currentTimeMillis();
        TotalF= Final - Inicio; 
        System.out.println("Inicio: "+Inicio);
        System.out.println("Fin: "+Final);
        System.out.println("Total: "+TotalF);
        JOptionPane.showMessageDialog(this, "El total es: "+Total+"\n"+"Soltar Pulsar: "+SoltarPulsar+"r\n"+"PP= "+PP+"\n"+"TotalFinal: "+TotalF+"Permanencia: "+Permanencia+"\n"+"Ausencia: "+Ausencia);
           Reporte[intentos]= Total;
           SoltarPulsar= SoltarPulsar * -1;
           RsoltarPulsar[intentos]= SoltarPulsar;
           ArrayPP[intentos]= PP;
           ArrayTF[intentos]= TotalF;
          
        intentos++;
     
        jLabel2.setText("Intentos: "+intentos);
        if(intentos==3){
            jTextArea1.setText("");
            
            for(int i=0;i<Reporte.length;i++){
                jTextArea1.append("Prueba "+i+" = "+Reporte[i]+ " | "+RsoltarPulsar[i]+" | "+ArrayPP[i]+" | "+ArrayTF[i]   +'\n');
                
            }
            
        }
        
        
//Ya lo importante:        
        for(int i=0;i<Pulsada.length;i++){
jTextArea1.append("Resultados Pulsada: "+i+" = "+Pulsada[i]+'\n');            
        }for(int i=0;i<Soltada.length;i++){
jTextArea1.append(">Resultados Soltada: "+i+" = "+Soltada[i]+'\n');            
        }*/
        
        
 
        
    
    
}else{
    

System.out.println("MAL MAL :C");    
    
    }
    
    
}
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Total=0;
        TotalF=0;
        bandera1=0;
        bandera2=0;
        Inicio=0;
        Final=0;
        contador=0;
        PP=0;
        pulsada=0;
        finish=0;
        time_start=0;
        SoltarPulsar=0;
        SumSP=0;
        Pulso1=0;
        Pulso2=0;
        jTextField1.setText("");
        jTextArea1.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
        // TODO add your handling code here:
        String Caracteres = jTextField1.getText();
        if(Caracteres.length()>9){
            evt.consume();
            jTextArea1.setText("");
            JOptionPane.showMessageDialog(this, "La contraseña debe tener un máximo de 10 caracteres");
            dispose();
            View viu= new View();
            viu.show();
        } 
    }//GEN-LAST:event_jTextField1KeyTyped

    private void jTextField3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyPressed
        // TODO add your handling code here:
        Clave2=evt.getExtendedKeyCode();
if(Clave2==8){
dispose();
View.main(Pegar);
}
//ID_start= System.currentTimeMillis();
//Pul_ID[contador1]=ID_start;
//contador1++;
    }//GEN-LAST:event_jTextField3KeyPressed

    private void jTextField3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyReleased
        // TODO add your handling code here:
//ID_end= System.currentTimeMillis();
//Sol_ID[contador2]=ID_end;
//contador2++;
    }//GEN-LAST:event_jTextField3KeyReleased

    private void jTextField3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyTyped
        // TODO add your handling code here:
        String Caracteres = jTextField3.getText();
        if(Caracteres.length()>10){
            evt.consume();
            
            //JOptionPane.showMessageDialog(this, "El nombre debe ser de máximo 7 caracteres");            
            JOptionPane.showMessageDialog(this, "El nombre tiene muchos caracteres");            
            dispose();
            View viu= new View();
            viu.show();
        } 
    }//GEN-LAST:event_jTextField3KeyTyped

    /**
     * @param args the command line arguments
     */
    
public void nombre() throws IOException{

if(contador1==3){   
nS1= Soltada[0];
nS2= Soltada[1];
nS3= Soltada[2];
nP1= Pulsada[0];
nP2= Pulsada[1];
nP3= Pulsada[2];
nResultados[0]=nS1-nP1;
nResultados[1]=nP2-nS1;
nResultados[2]=nS2-nP2;
nResultados[3]=nP3-nS2;
nResultados[4]=nS3-nP3;
}if(contador1==4){   
nS1= Soltada[0];
nS2= Soltada[1];
nS3= Soltada[2];
nS4= Soltada[3];

nP1= Pulsada[0];
nP2= Pulsada[1];
nP3= Pulsada[2];
nP4= Pulsada[3];

nResultados[0]=nS1-nP1;
nResultados[1]=nP2-nS1;
nResultados[2]=nS2-nP2;
nResultados[3]=nP3-nS2;
nResultados[4]=nS3-nP3;
nResultados[5]=nP4-nS3;
nResultados[6]=nS4-nP4;    
}if(contador1==5){   
nS1= Soltada[0];
nS2= Soltada[1];
nS3= Soltada[2];
nS4= Soltada[3];
nS5= Soltada[4];

nP1= Pulsada[0];
nP2= Pulsada[1];
nP3= Pulsada[2];
nP4= Pulsada[3];
nP5= Pulsada[4];

nResultados[0]=nS1-nP1;
nResultados[1]=nP2-nS1;
nResultados[2]=nS2-nP2;
nResultados[3]=nP3-nS2;
nResultados[4]=nS3-nP3;
nResultados[5]=nP4-nS3;
nResultados[6]=nS4-nP4;
nResultados[7]=nP5-nS4;
nResultados[8]=nS5-nP5;
     
}if(contador1==6){   
nS1= Soltada[0];
nS2= Soltada[1];
nS3= Soltada[2];
nS4= Soltada[3];
nS5= Soltada[4];
nS6= Soltada[5];

nP1= Pulsada[0];
nP2= Pulsada[1];
nP3= Pulsada[2];
nP4= Pulsada[3];
nP5= Pulsada[4];
nP6= Pulsada[5];

nResultados[0]=nS1-nP1;
nResultados[1]=nP2-nS1;
nResultados[2]=nS2-nP2;
nResultados[3]=nP3-nS2;
nResultados[4]=nS3-nP3;
nResultados[5]=nP4-nS3;
nResultados[6]=nS4-nP4;
nResultados[7]=nP5-nS4;
nResultados[8]=nS5-nP5;
nResultados[9]=nP6-nS5;
nResultados[10]=nS6-nP6;
nResultados[11]=nP7-nS6;    
}if(contador1==7){   
nS1= Soltada[0];
nS2= Soltada[1];
nS3= Soltada[2];
nS4= Soltada[3];
nS5= Soltada[4];
nS6= Soltada[5];
nS7= Soltada[6];

nP1= Pulsada[0];
nP2= Pulsada[1];
nP3= Pulsada[2];
nP4= Pulsada[3];
nP5= Pulsada[4];
nP6= Pulsada[5];
nP7= Pulsada[6];

nResultados[0]=nS1-nP1;
nResultados[1]=nP2-nS1;
nResultados[2]=nS2-nP2;
nResultados[3]=nP3-nS2;
nResultados[4]=nS3-nP3;
nResultados[5]=nP4-nS3;
nResultados[6]=nS4-nP4;
nResultados[7]=nP5-nS4;
nResultados[8]=nS5-nP5;
nResultados[9]=nP6-nS5;
nResultados[10]=nS6-nP6;
nResultados[11]=nP7-nS6;
nResultados[12]=nS7-nP7;    
}

 for(int i=0;i<nResultados.length;i++){
     
if(nResultados[i]>0){
      jTextArea1.append("Resultados de Persona: "+i+" = "+nResultados[i]+'\n');
                //cambiar método de separación por si hace falta
Persona=Persona+Long.toString(nResultados[i])+",";

}     

          
                
            }  
Persona=Persona+" # ";         
    
Name=jTextField3.getText();
Operaciones(Persona, Name);    
    
}    
    
    
public void Operaciones(String persona,String Name) throws IOException{

int tam=0;    
    
S1= Soltada[0];
S2= Soltada[1];
S3= Soltada[2];
S4= Soltada[3];
S5= Soltada[4];
S6= Soltada[5];
S7= Soltada[6];
S8= Soltada[7];
S9= Soltada[8];
S10= Soltada[9];

P1= Pulsada[0];
P2= Pulsada[1];
P3= Pulsada[2];
P4= Pulsada[3];
P5= Pulsada[4];
P6= Pulsada[5];
P7= Pulsada[6];
P8= Pulsada[7];
P9= Pulsada[8];
P10= Pulsada[9];

Resultados[0]=S1-P1;
Resultados[1]=P2-S1;

Resultados[2]=S2-P2;
Resultados[3]=P3-S2;

Resultados[4]=S3-P3;
Resultados[5]=P4-S3;

Resultados[6]=S4-P4;
Resultados[7]=P5-S4;

Resultados[8]=S5-P5;
Resultados[9]=P6-S5;

Resultados[10]=S6-P6;
Resultados[11]=P7-S6;

Resultados[12]=S7-P7;
Resultados[13]=P8-S7;

Resultados[14]=S8-P8;
Resultados[15]=P9-S8;

Resultados[16]=S9-P9;
Resultados[17]=P10-S9;

Resultados[18]=S10-P10;
    jTextArea1.append("--------------------------------------------------------"+'\n');
    
tam=Resultados.length;    
tam=tam-1;
    
 for(int i=0;i<Resultados.length;i++){                
                jTextArea1.append("Resultados de I: "+i+" = "+Resultados[i]+'\n');
                //cambiar método de separación por si hace falta
if(i==tam){
cadena=cadena+Long.toString(Resultados[i]);
}else{
cadena=cadena+Long.toString(Resultados[i])+",";
}                

                
            } 
 //System.out.println("La cadena es: "+cadena);
 String NombreArchivo= jTextField3.getText()+".txt";
 //int user=Integer.parseInt(jTextField3.getText());
 m.Editar(persona,NombreArchivo, cadena,Name,exist);
 dispose();
 
    
}

public void borrarDatos(){

}

    
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View().setVisible(true);
            }
        });
        
        
       
        

        
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
